server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: kettle-scheduler
  profiles:
    active: dev
    include:
      - shiro
      - kettle
  aop:
    proxy-target-class: true
  data:
    redis:
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
constant:
  salt: kettle-scw
  hash-iterations: 10